### ISSUE TITLE
throw new ERR_INVALID_ARG_TYPE(name, 'string', value)

### ISSUE THREAD

**Issue by weiyunpeng** [midwayjs/bundle-helper#6]
node:internal/validators:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at relative (node:path:497:5)
    at \node_modules\@midwayjs\bundle-helper\dist\index.js:99:66     
    at Array.filter (<anonymous>)
    at EntryGenerator.run (\node_modules\@midwayjs\bundle-helper\dist\index.js:99:14)
    at Object.<anonymous> (\node_modules\@midwayjs\bundle-helper\bin\bundle.js:13:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by czy88840616** [comment]
是不是有空文件？

**Comment by weiyunpeng** [comment]
> 是不是有空文件？

没用找到空文件，要不加个判断？

**Comment by czy88840616** [comment]
你可以在源码里改改看是哪里的问题，确定了可以提pr，我没有事例也没法复现。

**Comment by weiyunpeng** [comment]
> 你可以在源码里改改看是哪里的问题，确定了可以提pr，我没有事例也没法复现。

node.decorators获取的是undefind
